# -*- coding: utf-8 -*-
"""Fact spec: every entry points at BLOCK INDICES in extracted/*.json.

The builder pulls sourceLine text verbatim from those blocks, so a sourceLine
can never contain words that are not in the packet. Ranges join with a space
because the source wraps sentences across paragraph boundaries.

None means: the source has no such section. Do not synthesize.
"""

SYS = "Systems Theories Review"
PM = "Post Modern Therapies Review"
PSY = "Psychodynamic"
HUM = "Humanistic-Existential Review"
CBT = "CBT interventions notes"

SPEC = {

"bowen": {
  "name": "Bowen Family Systems", "family": ["systems"], "doc": SYS,
  "changeMechanism": [4],
  "therapistRoles": [[6], [7], [8], [9]],
  "goals": [[11], [12], [13], [14], [15], [16], [17]],
  "concepts": [
    ("Triangles (Triangulation)", [19, 20]),
    ("Differentiation of Self", [21, 22]),
    ("Nuclear Family Emotional System", [23, 24, 25]),
    ("Family Projection Process", [28, 29, 30, 31]),
    ("Multigenerational Transmission Process", [35, 36, 37, 38]),
    ("Emotional Cutoff", [52, 53, 54]),
    ("Genogram", [55, 56]),
  ],
  "interventions": [
    ("Reduce emotional reactivity", [58]),
    ("Reframing", [59, 60]),
    ("Genogram", [61]),
    ("De-triangulation", [62, 63, 64]),
    ("Increasing Differentiation", [65, 66]),
    ("Teaching “I” Statements", [67]),
    ("Opening Cutoff Relationships", [68, 69]),
    ("Interacts with Family", [70, 71]),
    ("Models", [72]),
    ("Bibliotherapy", [73]),
  ],
  "phases": {"beginning": [[76], [77], [78]],
             "middle": [[80], [81], [82], [83]],
             "end": [[85]]},
  "examTips": [[4]],
},

"strategic": {
  "name": "Strategic Therapy", "family": ["systems"], "doc": SYS,
  "changeMechanism": [88],
  "therapistRoles": [[90], [91], [92]],
  "goals": [[94], [95]],
  "concepts": [],
  "interventions": [
    ("Paradoxical Directives", [97, 98, 99, 100]),
    ("Positioning", [101, 102, 103]),
    ("Homework", [104, 105, 106, 107]),
    ("Prescribing the Symptom", [108, 109]),
    ("Restraining", [110, 111]),
    ("Ordeals", [112, 113, 114]),
  ],
  "phases": {"beginning": [[117], [118], [119], [120]],
             "middle": [[122], [123], [124]],
             "end": [[126], [127], [128]]},
  "examTips": [],
},

"structural": {
  "name": "Structural Family Therapy", "family": ["systems"], "doc": SYS,
  "changeMechanism": [131],
  "therapistRoles": [[133], [134], [135]],
  "goals": [[137], [138], [139]],
  "concepts": [
    ("Alliances", [141]),
    ("Coalitions", [142, 143]),
    ("Power Hierarchy", [144, 145, 146]),
    ("Subsystems", [147, 148, 149]),
    ("Family Map", [150, 151, 152, 153]),
    ("Disengaged Boundaries", [154, 155]),
    ("Enmeshed Boundaries", [156, 157]),
  ],
  "interventions": [
    ("Joining", [159, 160]),
    ("Tracking", [161, 162]),
    ("Mimesis", [163]),
    ("Unbalancing", [164, 165]),
    ("Reframe", [166, 167]),
    ("Enactment", [168, 169, 170]),
    ("Boundary Making", [171, 172, 173, 174]),
  ],
  "phases": {"beginning": [[178], [179], [180], [181]],
             "middle": [[183], [184]],
             "end": [[186], [187], [188]]},
  "examTips": [],
},

"satir": {
  "name": "Satir Communications Therapy", "family": ["systems", "humanistic"], "doc": SYS,
  "changeMechanism": [191, 192],
  "therapistRoles": [[194], [195], [196], [197]],
  "goals": [[199, 200]],
  "concepts": [
    ("Incongruent Communication", [202]),
    ("Styles of Communication", [203, 204]),
    ("Placater", [206]),
    ("Blamer", [207]),
    ("Computer", [208]),
    ("Distracter", [209]),
    ("Leveler", [210]),
  ],
  "interventions": [
    ("Modeling Communication", [211, 212]),
    ("Family Life Chronology", [213, 214, 215, 216]),
    ("Family Sculpting", [217, 218]),
    ("Take Responsibility", [219, 220]),
    ("Metaphors and Storytelling", [221]),
    ("Transforming Rules", [222]),
  ],
  "phases": {"beginning": [[225], [226], [227]],
             "middle": [[229], [230]],
             "end": [[232, 233]]},
  "examTips": [],
},

"narrative": {
  "name": "Narrative Therapy", "family": ["postmodern"], "doc": PM,
  "changeMechanism": [3],
  "therapistRoles": [[5], [6], [7], [8]],
  "goals": [[10], [11], [12], [13]],
  "concepts": [
    ("Problem-Saturated Stories", [15]),
    ("Alternate Stories", [16]),
    ("Thick Story", [17]),
    ("Thin Story", [18]),
  ],
  "interventions": [
    ("Externalizing the Problem", [19]),
    ("Deconstructive Questions", [20]),
    ("Mapping the Influence", [21]),
    ("Unique Outcomes", [22]),
    ("Enlisting a Witness", [23]),
    ("Written Artifact", [24]),
    ("Re-authoring the story", [30]),
  ],
  "phases": {"beginning": [[33]],
             "middle": [[35], [36], [37], [38], [39]],
             "end": [[41], [42], [43]]},
  "examTips": [],
},

"solution-focused": {
  "name": "Solution-Focused Therapy", "family": ["postmodern"], "doc": PM,
  "changeMechanism": [46, 47],
  "therapistRoles": [[49]],
  "goals": [[51], [52]],
  "concepts": [],
  "interventions": [
    ("Exception Questioning", [54, 55, 56]),
    ("Formula First Session Task (FFST)", [57]),
    ("Miracle Questioning", [58, 59, 60, 61]),
    ("Scaling Questions", [62, 63, 64, 65, 66, 67]),
    ("Presupposing Change", [68, 69, 70]),
    ("Coping Questions", [71, 72]),
    ("Affirmations/Compliments", [73]),
  ],
  "phases": {"beginning": [[76], [77], [78], [79], [80]],
             "middle": [[82], [83], [84], [85], [86], [87]],
             "end": [[89]]},
  "examTips": [],
},

"object-relations": {
  "name": "Object Relations", "family": ["psychodynamic"], "doc": PSY,
  "changeMechanism": [3, 4],
  "therapistRoles": [[6], [7], [8]],
  "goals": [[10], [11], [12]],
  "concepts": [
    ("Objects", [14]),
    ("Internalization", [15]),
    ("Self- and Object-Representations", [16]),
    ("Ego", [17, 18]),
    ("Splitting", [19]),
    ("Projection", [20]),
    ("Projective Identification", [21]),
    ("Introjection", [22]),
    ("Identification", [23]),
  ],
  "interventions": [
    ("Establish a holding environment", [27]),
    ("Interpretation", [31]),
    ("Confront resistance and primitive defenses", [32]),
    ("Focus on transference/countertransference", [33]),
    ("Identify and process projective identification", [34]),
  ],
  "phases": {"beginning": [[27], [28], [29]],
             "middle": [[31], [32], [33], [34]],
             "end": [[36], [37], [38]]},
  "examTips": [[34]],
},

"self-psychology": {
  "name": "Self Psychology", "family": ["psychodynamic"], "doc": PSY,
  "changeMechanism": [41, 42],
  "therapistRoles": [[44], [45], [46]],
  "goals": [[48], [49]],
  "concepts": [
    ("Self-Objects", [51, 52]),
    ("Self-Object Needs", [53]),
    ("Mirroring", [54]),
    ("Optimal Frustration", [55, 56]),
    ("Mirroring Transference", [57]),
    ("Twinship Transference", [58]),
    ("Idealizing Transference", [59]),
    ("Adversarial Transference", [60, 61]),
    ("Experience-Near Empathy", [62, 63]),
  ],
  "interventions": [
    ("Establish a therapeutic holding environment", [66]),
    ("Demonstrate containment", [67]),
    ("Provide “experience-near” empathy", [68]),
    ("Repair disruptions of the self-object transference", [71]),
    ("Addressing enactments", [72]),
    ("Mourning loss of selfobjects", [74]),
    ("Mourning ambitions and fantasies", [75]),
    ("Identify alternative self-objects", [76]),
  ],
  "phases": {"beginning": [[66], [67], [68], [69]],
             "middle": [[71], [72], [73], [74], [75], [76]],
             "end": [[78], [79]]},
  "examTips": [],
},

"attachment": {
  "name": "Attachment-Based Therapy (Bowlby)", "family": ["psychodynamic"], "doc": PSY,
  "changeMechanism": [82, 83],
  "therapistRoles": [[85, 86], [87, 88, 89]],
  "goals": [[91, 92], [93], [94], [95]],
  "concepts": [
    ("Attachment Behavior System", [97, 98, 99, 100, 101]),
    ("Secure Attachment", [102, 103, 104, 105]),
    ("Preoccupied/Anxious Attachment", [106, 107, 108, 109, 110]),
    ("Dismissive/Avoidant Attachment", [111, 112, 113, 114, 115]),
    ("Fearful/Avoidant Attachment (Disorganized)", [116, 117, 118, 119]),
  ],
  "interventions": [
    ("Attunement", [122]),
    ("Provide a secure base", [123]),
    ("Collaboratively identifying attachment style", [124]),
    ("Explore disruptions", [126, 127]),
    ("Support affect regulation", [128]),
    ("Repair", [130]),
    ("Repair stage", [131]),
  ],
  "phases": {"beginning": [[122], [123], [124]],
             "middle": [[126, 127], [128]],
             "end": [[130], [131]]},
  "examTips": [[132]],
},

"client-centered": {
  "name": "Client Centered Therapy", "family": ["humanistic"], "doc": HUM,
  "changeMechanism": [2],
  "therapistRoles": [[11], [12], [13], [14], [15], [16], [17]],
  "goals": [[4], [5], [6], [7], [8], [9]],
  "concepts": [],
  "interventions": [],
  "phases": None,
  "examTips": [[18]],
},

"gestalt": {
  "name": "Gestalt Therapy", "family": ["humanistic"], "doc": HUM,
  "changeMechanism": [20],
  "therapistRoles": [[22], [23], [24], [28]],
  "goals": [[26]],
  "concepts": [
    ("Present moment awareness", [25]),
    ("Phenomenological description", [27]),
    ("Body awareness", [36]),
    ("Focus on process", [37]),
  ],
  "interventions": [
    ("Experiments", [29]),
    ("Repeating statement", [30]),
    ("Present experience while discussing the past", [31]),
    ("Empty chair", [32]),
    ("Top dog / underdog dialogue", [33]),
    ("Repeating words or exaggerating gestures", [34]),
    ("Standing up while speaking", [35]),
  ],
  "phases": None,
  "examTips": [],
},

"existential": {
  "name": "Existential Therapy", "family": ["humanistic"], "doc": HUM,
  "changeMechanism": [39],
  "therapistRoles": [[41]],
  "goals": [[42]],
  "concepts": [
    ("Focus on moment to moment", [43]),
    ("Holding", [44]),
    ("Mastering emotional pain", [45]),
    ("Givens in life", [46]),
    ("Imaginal death", [47]),
  ],
  "interventions": [
    ("“Imaginal death” exercises", [47]),
  ],
  "phases": None,
  "examTips": [],
},

"experiential": {
  "name": "Experiential / Symbolic Therapy (Whitaker)",
  "family": ["humanistic", "systems"], "doc": HUM,
  "changeMechanism": [50],
  "therapistRoles": [[52], [53]],
  "goals": [[55]],
  "concepts": [
    ("Battle for Structure", [57, 58]),
    ("Battle for Initiative", [59]),
    ("Trial of Labor", [60]),
    ("Activating Constructive Anxiety", [61]),
    ("Play, Humor, and “Craziness”", [62]),
  ],
  "interventions": [
    ("Battle for Structure", [57, 58]),
    ("Battle for Initiative", [59]),
    ("Trial of Labor", [60]),
    ("Activating Constructive Anxiety", [61]),
    ("Play, Humor, and “Craziness”", [62]),
  ],
  "phases": {"beginning": [[64]], "middle": [[65]], "end": [[66, 67]]},
  "examTips": [[57, 58], [59]],
},

"cbt": {
  "name": "CBT (interventions)", "family": ["cognitive-behavioral"], "doc": CBT,
  # Source is an intervention catalog. No Theory of Change, no Therapist's Role,
  # no Treatment Goals section exists. Null, not synthesized. See BUILD_BRIEF S3.
  "changeMechanism": None,
  "therapistRoles": None,
  "goals": None,
  "concepts": [],
  "interventions": [
    ("Psychoeducation on the negative triad", [1]),
    ("Socratic Questioning", [2, 3]),
    ("Reframing", [4, 5]),
    ("Cognitive Restructuring", [6, 7]),
    ("Homework", [8]),
    ("Self-Monitoring", [9]),
    ("Behavioral Experiments", [10, 11]),
    ("Systematic Desensitization", [14, 15, 19, 20, 21]),
    ("Anxiety Management Training", [22, 23, 26, 27, 28, 29]),
    ("Assertiveness Training", [30, 31, 32, 33, 34]),
    ("Behavioral Activation", [35]),
    ("Communication Skills Training", [36]),
    ("Downward Arrow", [37, 38]),
    ("Exposure", [39]),
    ("Finding Alternatives", [40]),
    ("Labeling Distortions", [41]),
    ("Mastery/Pleasure Ratings", [42]),
    ("Opposite Action", [43]),
    ("Problem-Solving Training", [44]),
    ("Relaxation Training", [45]),
    ("Successive Approximation", [46]),
    ("Three-Column Technique", [47]),
    ("Thought Record", [48]),
  ],
  "phases": {"beginning": [[51], [52], [53], [54], [55]],
             "middle": [[57], [58], [59], [60], [61], [62], [63]],
             "end": [[65], [66], [67]]},
  "examTips": [[45], [12], [13], [47], [48], [28], [1]],
},

}
